### ISSUE TITLE
Changing hyperlink color/underline?

### ISSUE THREAD

**Issue by angoodkind** [duetosymmetry/cv#1]
I am trying to change the color of the links, and underline them. I added the following to the preamble, but it just made the links red/pinkish. Any idea why?
```
\hypersetup{%
  colorlinks=true,% hyperlinks will be black
  linkcolor=green
  linkbordercolor=red,% hyperlink borders will be red
  pdfborderstyle={/S/U/W 1}% border style will be underline of width 1pt
}
```

**Comment by duetosymmetry** [comment]
I see a missing comma.

Also, this repo is not the right place for this question.
